### ISSUE TITLE
Question regarding version of Templater for the OCR script

### ISSUE THREAD

**Issue by Pika78** [shawngraham/obsidian-student-starter-vault#2]
Hello Pr Graham,
I first would like to thank you for making available this starter vault which is a great resource for historians, as it tailors this impressive tool to this specific field of studies.
I have downloaded it and started to use it. 
I have encountered the following problem with the OCR function in the Templater plug in.
When I open a picture in your stater-vault (which has version 1.7.1 of the Templater) it works perfectly as expected.
I have transferred exactly the structure of the vault into the vault in which I have my own work (which has version 1.12.0) and have configured the various options in  the same way as in your vault. However, I get the following error `The error message I get on the Console is Templater Error: Template parsing error, aborting. tp.user.ocr is not a function`. 
My question is the following : does you workflow work perfectly with the current version (1.12.0) of Templater ? or do you get the same type of error if you have upgraded to this version? What can I do to resolve this issue ? 
I have sent a mail to pmbauer the author of the script but he does not have the time to look into this. 
If you could shed any light on this question, I would appreciate it very much.
Many thanks for your help and your this useful starter kit.
With best regards

**Comment by shawngraham** [comment]
Hi - it _sounds_ like a something has changed in the later version of templaterr. I haven't used this with the latest version of templater, so off the top of my head I'm not sure what one might need to change. It's worth going through the obsidian forums though because there might be more elegant OCR solutions out there.
